# Generated by Django 5.0.4 on 2024-05-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DocumentoApp", "0002_alter_documento_documento"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Documento",
        ),
    ]
