# Generated by Django 5.0.4 on 2024-05-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codNNA", models.CharField(max_length=50)),
                ("institucion", models.CharField(max_length=100)),
                ("codProyecto", models.CharField(max_length=50)),
                ("proyecto", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=50)),
                ("apellido_materno", models.CharField(max_length=50)),
                ("nombres", models.CharField(max_length=100)),
                ("fechanacimiento", models.DateField()),
                ("rut", models.CharField(max_length=20)),
                ("fechaingreso", models.DateField()),
                ("fechaegreso", models.DateField(blank=True, null=True)),
                ("vigencia", models.CharField(max_length=50)),
                ("sexo", models.CharField(max_length=10)),
                ("Nacionalidad", models.CharField(max_length=50)),
                ("TipoAtencion", models.CharField(max_length=100)),
                ("CalidadJuridica", models.CharField(max_length=100)),
                ("DireccionNino", models.CharField(max_length=200)),
                ("RegionNino", models.CharField(max_length=50)),
                ("Comuna", models.CharField(max_length=50)),
                ("SolicitanteIngreso", models.CharField(max_length=100)),
                ("Tribunal", models.CharField(max_length=100)),
                ("Expediente", models.CharField(max_length=100)),
                ("CausalIngreso_1", models.CharField(max_length=200)),
            ],
        ),
    ]
