# Generated by Django 5.0.4 on 2024-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nna",
            name="codNNA",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="nna",
            name="rut",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
